# Generated by Django 6.1.1 on 2026-09-05 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('gst_no', models.CharField(blank=True, max_length=20)),
                ('drug_license_no', models.CharField(blank=True, max_length=50)),
                ('state', models.CharField(max_length=100)),
            ],
        ),
    ]
