# Generated by Django 6.1.1 on 2026-09-05 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('manufacturer', models.CharField(max_length=200)),
                ('pack', models.CharField(max_length=50)),
                ('hsn_code', models.CharField(max_length=20)),
                ('gst_rate', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
