# Generated by Django 6.1.1 on 2026-09-06 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_purchaseinvoice_supplier_alter_invoice_invoice_date_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='batch',
            unique_together={('product', 'batch_no')},
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reference_no', models.CharField(blank=True, max_length=100)),
                ('remarks', models.TextField(blank=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='core.customer')),
            ],
        ),
    ]
