# Generated by Django 6.1.1 on 2026-09-06 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_salesreturn_salesreturnitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesreturn',
            name='credit_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
