# Generated by Django 6.1.1 on 2026-09-07 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_salesreturn_credit_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_date', models.DateField()),
                ('remarks', models.TextField(blank=True)),
                ('return_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='batch',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='batch',
            constraint=models.CheckConstraint(condition=models.Q(('stock_qty__gte', 0)), name='stock_not_negative'),
        ),
        migrations.AddField(
            model_name='purchasereturn',
            name='purchase_invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.purchaseinvoice'),
        ),
        migrations.AddField(
            model_name='purchasereturnitem',
            name='purchase_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.purchaseitem'),
        ),
        migrations.AddField(
            model_name='purchasereturnitem',
            name='purchase_return',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.purchasereturn'),
        ),
    ]
