# Generated by Django 6.1.1 on 2026-09-07 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_purchasereturn_purchasereturnitem_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='batch',
            unique_together={('product', 'batch_no')},
        ),
    ]
