# Generated by Django 6.1.1 on 2026-09-07 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_batch_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='city',
            field=models.TextField(default='X'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='free_qty',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
