# Generated by Django 6.1.1 on 2026-09-09 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_company_city_alter_invoiceitem_free_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='state',
            field=models.CharField(default='BIHAR', max_length=100),
        ),
    ]
